{% set version = "1.0.2" %}

package:
  name: mkdocs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mkdocs/mkdocs-{{ version }}.tar.gz
  sha256: 91ba1d518fb29e7175e48d5a2be9dd775a2355347f86eeb69775abe8da47daf6

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - mkdocs = mkdocs.__main__:cli

requirements:
  build:
    - python
    - pip
  run:
    - python
    - click >=3.3
    - jinja2 >=2.7.1
    - livereload >=2.5.1
    - markdown >=2.3.1
    - pyyaml >=3.10
    - tornado >=5.0

test:
  imports:
    - mkdocs
    - mkdocs.commands
    - mkdocs.config
    - mkdocs.tests
    - mkdocs.tests.config
    - mkdocs.tests.utils
    - mkdocs.themes
    - mkdocs.themes.mkdocs
    - mkdocs.themes.readthedocs
    - mkdocs.utils
  commands:
    - mkdocs --help

about:
  home: http://www.mkdocs.org
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Project documentation with Markdown.'

extra:
  recipe-maintainers:
    - ocefpaf
