{% set version = "1.2.4" %}

package:
  name: mkdocs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mkdocs/mkdocs-{{ version }}.tar.gz
  sha256: 8e7970a26183487fe2a1041940c6fd03aa0dbe5549e50c3e7194f565cb3c678a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mkdocs = mkdocs.__main__:cli

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click >=3.3
    - ghp-import >=1.0
    - importlib-metadata >=3.10
    - jinja2 >=2.10.1
    - markdown >=3.2.1
    - mergedeep >=1.3.4
    - packaging >=20.5
    - pyyaml >=3.10
    - pyyaml-env-tag >=0.1
    - watchdog >=2.0

test:
  requires:
    - pip
  imports:
    - mkdocs
    - mkdocs.commands
    - mkdocs.config
    - mkdocs.contrib
    - mkdocs.contrib.search
    - mkdocs.structure
    - mkdocs.tests
    - mkdocs.tests.config
    - mkdocs.tests.structure
    - mkdocs.tests.utils
    - mkdocs.themes
    - mkdocs.themes.mkdocs
    - mkdocs.themes.readthedocs
    - mkdocs.utils
  commands:
    - pip check
    - mkdocs --help

about:
  home: http://www.mkdocs.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Project documentation with Markdown

extra:
  recipe-maintainers:
    - ocefpaf
